# Generated by Django 3.1.2 on 2020-10-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyMoveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('imgURL', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('data_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
