# Generated by Django 3.1.2 on 2020-10-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0003_auto_20201029_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='easymoveitem',
            name='author',
            field=models.CharField(default='Lena', max_length=50),
        ),
    ]
