# Generated by Django 3.1.2 on 2020-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0004_easymoveitem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('R', 'Regular_user'), ('A', 'Admin')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='easymoveitem',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='easymoveitem',
            name='imgURL',
            field=models.CharField(default='/static/img/item/empty.png', max_length=200),
        ),
    ]
