# Generated by Django 3.1.2 on 2020-10-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0005_auto_20201030_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='Falls Church, VA', max_length=50),
        ),
    ]
