# Generated by Django 3.1.2 on 2020-10-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0006_userinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
