# Generated by Django 3.1.2 on 2020-11-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0007_auto_20201031_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('commentTitle', models.CharField(max_length=200)),
                ('commentText', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyMove.easymoveitem')),
            ],
        ),
    ]
