# Generated by Django 3.1.2 on 2020-11-19 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EasyMove', '0010_auto_20201118_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='easymoveitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
