# Generated by Django 3.1.2 on 2020-11-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0012_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easymoveitem',
            name='imgURL',
        ),
        migrations.AddField(
            model_name='easymoveitem',
            name='item_img',
            field=models.ImageField(default='/static/img/item/empty.png', upload_to='static/img/item'),
        ),
    ]
