# Generated by Django 3.1.2 on 2020-12-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0013_auto_20201129_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easymoveitem',
            name='item_img',
            field=models.ImageField(upload_to='item_image'),
        ),
    ]
