# Generated by Django 3.1.2 on 2020-12-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMove', '0014_auto_20201210_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easymoveitem',
            name='item_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
