# Generated by Django 3.1.2 on 2020-11-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_details_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
